
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-09-13T07:44:01-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "a3c69943d69403272b05b0b2f599acf8a74b1ee9",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
